# ============================================================================
# SingN'Seek - Static Configuration
# ============================================================================
# This file contains configuration that remains constant across environments
# Environment-specific values (secrets, hosts, credentials) go in .env
# ============================================================================

# ============================================================================
# ELASTICSEARCH CONFIGURATION
# ============================================================================

elasticsearch:
  index_name: singnseek
  timeout: 30
  max_retries: 3
  retry_on_timeout: true

# ============================================================================
# EMBEDDINGS CONFIGURATION
# ============================================================================

embeddings:
  # Audio Embeddings Dimensions (MuQ model output)
  audio_dims: 512
  
  # Text Embeddings Dimensions (Vertex AI text-embedding-004)
  text_dims: 768

# ============================================================================
# SEARCH CONFIGURATION
# ============================================================================

search:
  # Hybrid Search Alpha: weight for text vs audio (0-1)
  # 0.6 means 60% text (BM25), 40% audio (vector similarity)
  hybrid_alpha: 0.6
  
  # Number of top results to return
  top_k: 10
  
  # Number of results to consider for reranking
  rerank_top_k: 20

# ============================================================================
# MUQ MODEL SETTINGS (Audio Embeddings)
# ============================================================================

muq:
  model: OpenMuQ/MuQ-large-msd-iter
  sample_rate: 24000

# ============================================================================
# VERTEX AI MODEL SETTINGS
# ============================================================================

vertex_ai:
  text_embedding_model: text-embedding-004
  rerank_model: gemini-1.5-flash-002
