version: '3.8'

services:
  singnseek:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: singnseek-app
    ports:
      - "8501:8501"
    volumes:
      # Mount source code for development (optional - remove for production)
      - ./src:/app/src
      - ./dataset:/app/dataset
      - ./images:/app/images
    # Load environment variables from .env file
    env_file:
      - .env
    environment:
      # Streamlit configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Application environment
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
