[project]
name = "singnseek"
version = "0.1.0"
description = "Song stuck in your head? Find it by humming"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elasticsearch>=9.1.1",
    "streamlit>=1.50.0",
    "watchdog>=6.0.0",
]
