# ============================================================================
# SingN'Seek - Static Configuration
# ============================================================================
# This file contains configuration that remains constant across environments
# Environment-specific values (secrets, hosts, credentials) go in .env
# ============================================================================

# ============================================================================
# ELASTICSEARCH CONFIGURATION
# ============================================================================

elasticsearch:
  index_name: singnseek
  timeout: 30
  max_retries: 3
  retry_on_timeout: true

# ============================================================================
# EMBEDDINGS CONFIGURATION
# ============================================================================

embeddings:
  # Audio Embeddings Dimensions (MuQ model output)
  # MuQ-large-msd-iter outputs 1024-dimensional embeddings
  audio_dims: 1024
  
  # Text Embeddings Dimensions (Vertex AI text-embedding-004)
  text_dims: 768

# ============================================================================
# SEARCH CONFIGURATION
# ============================================================================

search:
  # Hybrid Search Alpha: weight for text vs audio (0-1)
  # 0.6 means 60% text (BM25), 40% audio (vector similarity)
  hybrid_alpha: 0.6
  
  # Number of top results to return
  top_k: 5
  
  # Number of results to consider for reranking
  rerank_top_k: 10

# ============================================================================
# MUQ MODEL SETTINGS (Audio Embeddings)
# ============================================================================

muq:
  model: OpenMuQ/MuQ-large-msd-iter
  sample_rate: 24000

# ============================================================================
# VERTEX AI MODEL SETTINGS
# ============================================================================

vertex_ai:
  text_embedding_model: text-embedding-004
  rerank_model: gemini-1.5-flash-002

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  
  # Log file settings
  file: server.log
  max_bytes: 10485760  # 10MB
  backup_count: 5
  
  # Elasticsearch logging (for observability dashboard)
  elasticsearch:
    enabled: true
    index_name: singnseek-logs
    index_frequency: daily  # daily, weekly, monthly, yearly

# ============================================================================
# UI FEATURES CONFIGURATION
# ============================================================================

ui:
  # Enable/disable the Save Song button in Add New Song page
  enable_save_song: true
