# Elasticsearch Configuration
# Replace with your actual Elasticsearch credentials

elasticsearch:
  # For local Elasticsearch
  host: "localhost"
  port: 9200
  scheme: "http"
  
  # For Elastic Cloud (serverless)
  # cloud_id: "your-cloud-id"
  
  # API Key authentication (recommended)
  api_key: "your-api-key-here"
  
  # OR Basic authentication
  # username: "elastic"
  # password: "your-password"
  
  # Index settings
  index_name: "songs"
  
  # Request timeout (seconds)
  timeout: 30
  
  # Retry settings
  max_retries: 3
  retry_on_timeout: true

# Embedding dimensions
embeddings:
  audio_dims: 512  # MuQ-large-msd-iter output dimension
  text_dims: 768   # Vertex AI text-embedding dimension
  
# Search settings
search:
  hybrid_alpha: 0.6  # Weight for BM25 vs vector search (0.6 = 60% BM25, 40% vector)
  top_k: 10  # Number of results to return
  rerank_top_k: 20  # Number of results to fetch before re-ranking
